# Generated by Django 2.2.3 on 2019-08-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190823_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='intro',
            field=models.TextField(blank=True),
        ),
    ]
