# Generated by Django 2.2.3 on 2019-08-24 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_author_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='date',
        ),
    ]
