# Generated by Django 2.2.3 on 2019-09-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190901_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreimage',
            name='credit',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
